[template]
src = "slaveproxy.cnf.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
uid = 0
gid = 0
mode = "0644"
keys = [
  "/haproxy/mysqlslave",
]

check_cmd = "/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -c"
reload_cmd = "/etc/init.d/haproxy reload"
